### ISSUE TITLE
demo 下 npm run watch 报错

### ISSUE THREAD

**Issue by sfyr111** [cyan33/learn-react-source-code#11]
ERROR in ../dilithium/index.js
Module build failed: ReferenceError: Unknown plugin "transform-class-properties" specified in "/Users/yangran/project/learn-react-source-code/dilithium/package.json" at 0, attempted to resolve relative to "/Users/yangran/project/learn-react-source-code/dilithium"

**Comment by cyan33** [comment]
It works well on my end. Can you try deleting the node_modules and re-run `npm install`?

**Comment by zaleGZL** [comment]
I have the same error. 
![image](https://user-images.githubusercontent.com/20339327/39664154-d1e2e420-50b1-11e8-8809-23d18b3eb921.png)

**Comment by cyan33** [comment]
I've tested again and it works on my end. 

This error is likely because of it doesn't have `transform-class-properties` installed (I don't know why because it's already been specified in `package.json`). You might want to try this:

```
npm install babel-plugin-transform-class-properties
```
