### ISSUE TITLE
关于Day1-Guidance里面有一点小疑惑

### ISSUE THREAD

**Issue by lazysheep666** [cyan33/learn-react-source-code#18]
由于我们在使用 React 实现组件化的时候，使用的有且只有 CompositeComponent，所以，我们的每一个组件，其实都是一个 Component。但是当 React 试图去 render 这些组件的时候，**会将 Element 转化成 Component**，进而转化成真正的 DOM 节点。

这里为什么不是将**Component转化为Element**因为看到[React Components, Elements, and Instances](https://reactjs.org/blog/2015/12/18/react-components-elements-and-instances.html)说**type为function或者class的element**最终都会转换为**type为string的element**
如理解有误请大佬指出。

**Comment by cyan33** [comment]
Hey @lazysheep666,

That's a good question. Sorry for not having made it clear in the first place.

I think both are right, depends on how you understand the flow of rendering.

When I try to render `<App>` **(element)**, I need to instantiate the `class App` **(component)**. And when after that we try to render its children components, we go to its render method and build the **element** tree. And then we repeat the process.

So it's actually:

```
element -> component -> element -> component -> element ...
```

Hope this answers your question.

**Comment by lazysheep666** [comment]
Thanks @cyan33    :)
